# Generated by Django 4.0.4 on 2022-06-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_artwork_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
