# Generated by Django 4.0.4 on 2022-06-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_artwork_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
