# Generated by Django 4.0.4 on 2022-06-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_artwork_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
