# Generated by Django 4.0.4 on 2022-06-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_artwork_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
