# Generated by Django 4.0.4 on 2022-06-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_artwork_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='previews/'),
        ),
    ]
