# Generated by Django 4.0.4 on 2022-06-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_artwork_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('investment', models.IntegerField()),
                ('type', models.CharField(choices=[('Character Model', 'character_model'), ('ArchViz', 'archviz'), ('Abstract', 'abstract')], max_length=50)),
                ('details', models.TextField()),
            ],
        ),
    ]
