# Generated by Django 4.0.4 on 2022-06-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='f_name',
            field=models.CharField(max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='request',
            name='l_name',
            field=models.CharField(max_length=20, verbose_name='Last Name'),
        ),
    ]
