# Generated by Django 4.0.4 on 2022-06-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_request_f_name_alter_request_l_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('character_model', 'Character Model'), ('archviz', 'ArchViz'), ('abstract', 'Abstract')], max_length=50),
        ),
    ]
