# Generated by Django 4.0.4 on 2022-06-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('character_model', 'Character Model'), ('archviz', 'ArchViz'), ('abstract', 'Abstract')], default='character_model', max_length=50),
        ),
    ]
